# Generated by Django 6.0.7 on 2026-07-16 22:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('plataforma', models.CharField(max_length=50)),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateField(default=datetime.date.today)),
                ('data_devolucao', models.DateField()),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jogo')),
            ],
        ),
    ]
