# Generated by Django 6.0.7 on 2026-07-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='alugado',
            field=models.BooleanField(default=False),
        ),
    ]
