# Generated by Django 6.0.7 on 2026-07-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jogo_alugado'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locacao',
            name='dias',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
